In [1]:
%cd ../..

/gpfs/data/schambralab/quantitativeRehabilitation/__lab_member_homes/victor/cvfm4rehab

In [2]:
from postprocess.ia.eval import (
    answers_for_model,
    fm_scores_for_model,
    metrics_for_model,
    metrics_for_models
)

In [ ]:
MODEL = "qwen2_5_vl_7b"
task1 = ("strokerehab_ia1_3_30", "strokerehab_ia1_31_33")  # simultaneous
task2 = ("strokerehab_ia2_3_30", "strokerehab_ia2_31_33")  # individual

print(metrics_for_model("qwen2_5_vl_7b", tasks=task1))
print(metrics_for_model("qwen2_5_vl_7b", tasks=task2))

{'accuracy': 0.325, 'apd': 29.5, 'mtsd': 28.0}
{'accuracy': 0.4083333333333333, 'apd': 26.25, 'mtsd': 25.25}

In [45]:
df = fm_scores_for_model(MODEL, tasks=task1)

def pivot_fm_scores(df):
    df_long = df.melt(
        id_vars=['patient', 'fm_item'],
        value_vars=['pred_score', 'gt_score'],
        var_name='score_type',
        value_name='score'
    )
    df_long['col'] = df_long['score_type'] + "_" + df_long['patient']
    out = df_long.pivot(index="fm_item", columns="col", values="score")
    return out

pivot_fm_scores(df)

col,gt_score_C00011,gt_score_S0001,gt_score_S00021,gt_score_S0005,pred_score_C00011,pred_score_S0001,pred_score_S00021,pred_score_S0005
fm_item,,,,,,,,
3,2,2,1,2,1,1,0,0
4,2,2,0,2,1,2,1,1
5,2,2,1,2,2,1,1,1
6,2,2,0,2,2,2,2,2
7,2,2,0,2,2,2,2,2
8,2,1,0,2,2,2,1,1
9,2,2,0,2,1,1,1,1
10,2,1,0,2,1,1,1,1
11,2,2,0,2,1,1,1,1
12,2,2,0,2,2,2,1,1
13,2,0,0,2,0,0,0,0
14,2,1,0,2,0,0,0,0
15,2,0,0,2,0,0,0,0
16,2,0,0,2,0,0,0,0
17,2,0,0,2,0,0,0,0
18,2,0,1,1,0,0,0,0
19,2,2,0,2,0,0,0,0
20,2,1,0,2,0,0,0,0
21,2,0,0,2,0,0,0,0
22,2,0,0,2,0,0,0,0
23,2,1,0,2,0,0,0,0
24,2,2,1,2,1,1,2,1
25,2,1,0,2,1,1,1,1
26,2,2,0,2,0,0,0,0
27,2,1,0,2,0,0,0,0
28,2,1,0,2,0,0,0,0
29,2,2,0,2,0,0,0,0
30,2,2,0,2,2,0,0,0
31,2,2,0,2,1,1,1,1
32,2,1,0,2,1,1,1,1
33,2,1,0,2,2,2,2,2

In [46]:
df = answers_for_model(MODEL, tasks=task1)

In [47]:
def pivot_answers(df):
    melted_df = df.melt(
        id_vars=['patient', 'qid'],
        value_vars=['answer'],
        var_name='answer_type',
    )
    melted_df.drop(columns=['answer_type'], inplace=True)
    melted_df.rename({'value': 'answer'}, axis=1, inplace=True)
    out = (
        melted_df
        .pivot(index="qid", columns="patient", values="answer")
        .add_suffix("_answer")
    )
    return out

# df_long['col'] = df_long['score_type'] + "_" + df_long['patient']
# out = df_long.pivot(index="fm_item", columns="col", values="score")

In [48]:
pivot_answers(df).to_csv("scrap.csv", index=True)

In [49]:
df = fm_scores_for_model(MODEL, tasks=task2)
pivot_fm_scores(df)

col,gt_score_C00011,gt_score_S0001,gt_score_S00021,gt_score_S0005,pred_score_C00011,pred_score_S0001,pred_score_S00021,pred_score_S0005
fm_item,,,,,,,,
3,2,2,1,2,1,1,1,1
4,2,2,0,2,2,1,1,1
5,2,2,1,2,2,2,1,2
6,2,2,0,2,2,2,1,2
7,2,2,0,2,2,2,1,2
8,2,1,0,2,2,2,1,2
9,2,2,0,2,1,1,1,1
10,2,1,0,2,1,1,1,1
11,2,2,0,2,2,2,1,2
12,2,2,0,2,1,2,0,1
13,2,0,0,2,0,0,0,0
14,2,1,0,2,0,0,0,0
15,2,0,0,2,0,0,0,0
16,2,0,0,2,0,0,0,0
17,2,0,0,2,0,0,0,0
18,2,0,1,1,0,0,0,0
19,2,2,0,2,0,0,0,0
20,2,1,0,2,0,0,0,0
21,2,0,0,2,0,0,0,0
22,2,0,0,2,0,0,0,0
23,2,1,0,2,0,0,0,0
24,2,2,1,2,1,2,1,2
25,2,1,0,2,1,1,1,1
26,2,2,0,2,0,0,0,0
27,2,1,0,2,0,0,0,0
28,2,1,0,2,0,0,0,0
29,2,2,0,2,0,0,0,0
30,2,2,0,2,2,0,0,0
31,2,2,0,2,1,1,1,1
32,2,1,0,2,1,1,1,1
33,2,1,0,2,2,2,2,2

In [50]:
df = answers_for_model(model=MODEL, tasks=task2)
pivot_answers(df).to_csv("scrap.csv", index=True)